version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=628513987074.dkr.ecr.ap-northeast-1.amazonaws.com/my-app-repo:latest
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 628513987074.dkr.ecr.ap-northeast-1.amazonaws.com/
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI
      - echo Writing image definitions file...
      - printf '[{"name":"MyContainer","imageUri":"%s"}]' $REPOSITORY_URI > imagedefinitions.json

artifacts:
  files: imagedefinitions.json

cache:
  paths:
    - '/root/.npm/*'