version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 628513987074.dkr.ecr.ap-northeast-1.amazonaws.com/sample-demo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 628513987074.dkr.ecr.ap-northeast-1.amazonaws.com/sample-demo:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 628513987074.dkr.ecr.ap-northeast-1.amazonaws.com/sample-demo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"MyContainer","imageUri":"628513987074.dkr.ecr.ap-northeast-1.amazonaws.com/sample-demo:latest"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json

cache:
  paths:
    - '/root/.npm/*'